// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AddTask(arg1:domain.Task):Promise<void>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetAllTasks():Promise<Array<domain.Task>>;

export function UpdateStatus(arg1:number,arg2:boolean):Promise<void>;
