// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1) {
  return window['go']['main']['TaskBackend']['AddTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['TaskBackend']['DeleteTask'](arg1);
}

export function GetAllTasks() {
  return window['go']['main']['TaskBackend']['GetAllTasks']();
}

export function UpdateStatus(arg1, arg2) {
  return window['go']['main']['TaskBackend']['UpdateStatus'](arg1, arg2);
}
